<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseAppHost>true</UseAppHost>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.5.0</Version>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.PointOfService">
      <HintPath>lib\Microsoft.PointOfService.dll</HintPath>
    </Reference>
    <Reference Include="System.Management" />
    <PackageReference Include="ZXing.Net" Version="0.16.9" />
    <PackageReference Include="System.Resources.Extensions" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Icons\.ico Files\*.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
